      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure ML CLI
        run: pip install azure-ai-ml

      - name: Submit Azure ML Job
        run: az ml job create --file job.yml

              - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        run: az login --use-device-code

      - name: Submit Azure Job
        run: az ml job create --file job.yml